# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pandas as pd
import numpy as np
from binance import Client
import seaborn as sns
from PyQt5 import QtCore, QtGui, QtWidgets
#from PyQt5.QtWidgets import QDialog
import time
from PyQt5.QtGui import QPixmap

from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
import matplotlib.pyplot as plt
from datetime import date
from statsmodels.tsa.stattools import ccf, grangercausalitytests
from statsmodels.tsa.vector_ar.var_model import VAR
from scipy.signal import cwt, ricker
from scipy.ndimage import gaussian_filter



class Ui_MainWindow(object):
    def __init__(self):
        text_file = open("./data.txt", "r")
        self.rd=text_file.read()
        text_file.close()

        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        #MainWindow.resize(700, 500)
        MainWindow.setFixedSize(1200, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.day = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        self.day.setFont(font)
        self.day.setObjectName("day")
        self.day.addItem("")
        self.day.addItem("")
        self.day.addItem("")
        self.day.addItem("")
        self.horizontalLayout.addWidget(self.day)
        self.period = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        self.period.setFont(font)
        self.period.setObjectName("period")
        self.period.addItem("")
        self.period.addItem("")
        self.period.addItem("")
        self.period.addItem("")
        self.period.addItem("")
        self.horizontalLayout.addWidget(self.period)
        self.down = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        self.down.setFont(font)
        self.down.setObjectName("down")
        self.horizontalLayout.addWidget(self.down)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.date = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date.sizePolicy().hasHeightForWidth())
        self.date.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        self.date.setFont(font)
        self.date.setObjectName("date")
        self.horizontalLayout_2.addWidget(self.date)
        self.load = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        self.load.setFont(font)
        self.load.setObjectName("load")
        self.horizontalLayout_2.addWidget(self.load)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.deneme = QtWidgets.QLabel(self.centralwidget)
        self.deneme.setText("")
        self.deneme.setObjectName("deneme")
        self.verticalLayout.addWidget(self.deneme)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.line = QtWidgets.QFrame(self.centralwidget)
        #self.line.setMinimumSize(QtCore.QSize(0, 0))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.coin1 = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coin1.sizePolicy().hasHeightForWidth())
        self.coin1.setSizePolicy(sizePolicy)
        self.coin1.setMinimumSize(QtCore.QSize(60, 20))
        #self.coin1.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        self.coin1.setFont(font)
        self.coin1.setObjectName("coin1")
        self.coin1.setText("")
        self.coin1.setEnabled(False)
        self.horizontalLayout_6.addWidget(self.coin1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_3.setShortcut("Return")
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_3.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        
        self.table = QtWidgets.QTableWidget(MainWindow)
        font.setBold(True)
        self.table.setFont(font)
        #self.table.setGeometry(QtCore.QRect(60, 50, 200, 150))
        self.table.setSizePolicy(sizePolicy)
        self.table.setObjectName("table")
        self.table.setColumnCount(2)
        self.table.setRowCount(10)
        self.table.setMaximumWidth(300)
        self.table.setColumnWidth(0,140)
        self.table.setColumnWidth(1,140)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        
        self.table.setEnabled(False)
        self.verticalLayout_4.addWidget(self.table)
        self.horizontalLayout_5.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)

        font.setBold(False)
        self.cn_1=QtWidgets.QLineEdit(self.groupBox_5)
        self.cn_1.setFont(font)
        self.cn_1.setMinimumWidth(40)
        self.cn_1.setMaximumWidth(80)
        self.cn_1.setEnabled(False)
        self.ok=QtWidgets.QLabel(self.groupBox_5)
        
        self.label_5.setText( "Coin1")
        self.ok.setText("Coin2")        
        
        self.cn_2=QtWidgets.QLineEdit(self.groupBox_5)
        
        self.cn_2.setFont(font)
        self.cn_2.setMinimumWidth(40)
        self.cn_2.setMaximumWidth(80)
        self.cn_2.setEnabled(False)
        self.oran=QtWidgets.QLabel(self.groupBox_5)
        self.oran.setText(".....%")
        self.oran.setMinimumWidth(80)
        self.drw=QtWidgets.QPushButton(self.groupBox_5)
        self.drw.setMinimumWidth(140)
        self.drw.setEnabled(False)
        self.wavelet_button = QtWidgets.QPushButton(self.groupBox_5)
        self.wavelet_button.setText("Wavelet Coherence")
        self.wavelet_button.setEnabled(False)
        self.ternary_button = QtWidgets.QPushButton(self.groupBox_5)
        self.ternary_button.setText("Ternary")
        self.ternary_button.setEnabled(False)
        self.horizontalLayout_7.addWidget(self.cn_1)
        self.horizontalLayout_7.addWidget(self.ok)
        self.horizontalLayout_7.addWidget(self.cn_2)
        self.horizontalLayout_7.addWidget(self.oran)
        self.horizontalLayout_7.addWidget(self.drw)
        self.horizontalLayout_7.addStretch()   
        self.horizontalLayout_7.addWidget(self.wavelet_button)
        self.horizontalLayout_7.addWidget(self.ternary_button)
        
        
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        font = QtGui.QFont()
        font.setItalic(True)
        
        self.horizontalLayout_5.addWidget(self.groupBox_5)

        self.verticalLayout.addLayout(self.horizontalLayout_5)
        
        self.verticalLayout.addStretch()

        # New GroupBox for Advanced Methods
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_6.setTitle("Advanced Lead-Lag Analysis")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.lag_button = QtWidgets.QPushButton(self.groupBox_6)
        self.lag_button.setText("Lagged Correlation")
        self.lag_button.setEnabled(False)
        self.horizontalLayout_8.addWidget(self.lag_button)
        self.granger_button = QtWidgets.QPushButton(self.groupBox_6)
        self.granger_button.setText("Granger Causality")
        self.granger_button.setEnabled(False)
        self.horizontalLayout_8.addWidget(self.granger_button)

        #self.horizontalLayout_8.addWidget(self.wavelet_button)
        self.var_button = QtWidgets.QPushButton(self.groupBox_6)
        self.var_button.setText("VAR Model")
        self.var_button.setEnabled(False)
        self.horizontalLayout_8.addWidget(self.var_button)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.analysis_result = QtWidgets.QTextEdit(self.groupBox_6)
        self.analysis_result.setReadOnly(True)
        self.verticalLayout_6.addWidget(self.analysis_result)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.yz=QtWidgets.QLabel("This application developed by Mustafa TASCI")
        self.yz.setFont(font)
        self.sonh=QtWidgets.QHBoxLayout()
        self.sonh.addStretch()
        self.sonh.addWidget(self.yz)
        self.verticalLayout.addLayout(self.sonh)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        
        
        self.label_pic = QtWidgets.QLabel(self.groupBox_5)
        pixmap = QPixmap('output.png')
        self.label_pic.setPixmap(pixmap)
        #self.setCentralWidget(self.label_pic)
        self.label_pic.resize(250, 125)
        #self.resize(pixmap.width(160), pixmap.height(120))
        self.verticalLayout_5.addWidget(self.label_pic)
        self.figure = plt.figure(figsize=(12, 6), dpi=80)
        
        self.down.clicked.connect(self.dl)
        self.load.clicked.connect(self.load_file)
        self.table.cellClicked.connect(self.cell_clicked)
        self.drw.clicked.connect(self.ciz)
        self.retranslateUi(MainWindow)
        self.k=0
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.load.clicked.connect(self.load_file)
        self.pushButton_3.clicked.connect(self.corel)
        #self.coin2.currentTextChanged.connect(self.ciz)
        self.deneme.setText("The data download process takes approximately 3-5 minutes. If you have downloaded the data before, you can continue directly from the upload section.")

        # Connect new buttons
        self.lag_button.clicked.connect(self.calculate_lagged_correlation)
        self.granger_button.clicked.connect(self.calculate_granger_causality)
        self.wavelet_button.clicked.connect(self.plot_wavelet_coherence)

        self.var_button.clicked.connect(self.calculate_var_model)
    
    
    def cell_clicked(self, row, column):
        try:
            item = self.table.item(row, 0)
            self.cn_2.setText(item.text().upper())
            self.ciz()
        except:
            print("aaaaa")
        
    
    def dl(self):
        reg = str(date.today()) + " ---> " + self.day.currentText() + " ---> Period " + self.period.currentText() + "---> "
        text_file = open("./data.txt", "w")
        text_file.write(reg)
        text_file.close()
        self.client = Client()
        info = self.client.get_exchange_info()
        sembol = [x['symbol'] for x in info['symbols']]
        sembol_usd = [symbol for symbol in sembol if symbol.endswith('USDT')]
        s = len(sembol_usd)
        dfs = []
        i = 0
        self.deneme.setText("Downloading....")
        for coin in sembol_usd:
            i += 1
            dfs.append(self.getdetailydata(coin))
            self.progressBar.setValue(round(i * (100 / s)))
        mergedf = pd.concat(dict(zip(sembol_usd, dfs)), axis=1)
        # Kapanış ve Açılış fiyatlarını al
        closedf = mergedf.loc[:, mergedf.columns.get_level_values(1).isin(['Close'])]
        opendf = mergedf.loc[:, mergedf.columns.get_level_values(1).isin(['Open'])]
        closedf.columns = closedf.columns.droplevel(1)
        opendf.columns = opendf.columns.droplevel(1)
        # Yüzde değişim: (Close - Open) / Open
        percentdf = (closedf - opendf) / opendf * 100  # Yüzde cinsinden
        percentdf.to_csv("percentdf.csv")
        self.load_file()
        
    def getdetailydata(self,symbol):
        msg=self.day.currentText()+" ago UTC"
        
        frame=pd.DataFrame(self.client.get_historical_klines(symbol,
                            self.period.currentText(),msg))
        if(len(frame)>0):
            frame=frame.iloc[:,:5]
            frame.columns=["Time","Open","High","Low","Close"]
            frame.set_index("Time")
            frame.index=pd.to_datetime(frame.index,unit="ms")
            frame=frame.astype(float)
            return frame
       # '4h','90 days ago UTC'



    def load_file(self):  
        if self.k == 0:
            self.pushButton_3.setEnabled(True)
            self.drw.setEnabled(True)
            self.cn_1.setEnabled(True)
            self.cn_2.setEnabled(True)
            self.coin1.setEnabled(True)
            self.table.setEnabled(True)
            self.lag_button.setEnabled(True)
            self.granger_button.setEnabled(True)
            self.wavelet_button.setEnabled(True)
            self.ternary_button.setEnabled(True)
            self.var_button.setEnabled(True)
            self.percentdf = pd.read_csv("logretdf.csv")
            self.cordf=self.percentdf.corr()
            self.percentdf = self.percentdf.drop([0])  # İlk satır genellikle NaN
            #self.percentdf = self.percentdf.drop(columns=["Unnamed: 0"])
            self.deneme.setText("Loading....")
            self.k += 1
            for i in range(101):
                time.sleep(0.001)
                self.progressBar.setValue(i)
            msg = "All Data Loaded"
            self.deneme.setText(msg)
        else:
            self.k = 0
        

            
        
    def corel(self):
        try:
            c1=self.coin1.text().upper()+"USDT"
            aaa=self.cordf[c1].nlargest(11)
            
            self.cn_1.setText(self.coin1.text().upper())
            self.cn_2.setText(aaa.index[1][:-4].upper())

            for i in range(0,10):
                a=aaa.index[i+1][:-4]
                b=str(int(aaa.iloc[i+1]*100))+"%"
                self.table.setItem(i,0, QtWidgets.QTableWidgetItem(a))
                
                item = QtWidgets.QTableWidgetItem(b)
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.table.setItem(i, 1,item)
                
                #self.coin2.setItemText(i,a)
                if(self.k==0):
                    self.ciz()
                    self.k=1
            self.ciz1()

        except KeyError:
            print("Coin not found in binance. Please write correct coin ")
            
    def ciz1(self):
        try:
            c1 = self.cn_1.text().upper() + "USDT"
            c2 = self.cn_2.text().upper() + "USDT"
            series1 = self.percentdf[c1].dropna()
            series2 = self.percentdf[c2].dropna()
            min_len = min(len(series1), len(series2))
            series1 = series1[:min_len]
            series2 = series2[:min_len]
            
            # En yüksek lag korelasyonunu hesapla
            lag_range = range(-10, 11)
            cross_corrs = ccf(series1, series2, unbiased=False)[:len(lag_range)]
            max_lag = lag_range[np.argmax(np.abs(cross_corrs))]
            max_corr = np.max(np.abs(cross_corrs))
            orn = f"{int(max_corr*100)}% (Lag {max_lag})"
            self.oran.setText(orn)
            
            # Yüzde değişim grafikleri (kümülatif değil, ham yüzde)
            plot_df = pd.DataFrame({
                c1: series1,
                f"{c2} (Lag {max_lag})": series2.shift(max_lag)  # İkinci coin'i lag ile kaydır
            })
            
            self.figure.clear()
            plt.tight_layout()
            sns.set_style("darkgrid")
            self.figure = sns.lineplot(data=plot_df)
            plt.title(f"{c1} vs {c2} Percent Change (Lag {max_lag})")
            plt.ylabel("% Change ((Close - Open) / Open)")
            
            fig = self.figure.get_figure()
            fig.savefig("output.png")
            pixmap = QPixmap("output.png")
            self.label_pic.setPixmap(pixmap)
        except KeyError:
            self.deneme.setText("Coin not found in Binance. Please write correct coin.")

    def ciz(self):
        try:
            c1=self.cn_1.text().upper()+"USDT"
            c2=self.cn_2.text().upper()+"USDT"
            orn=str(int(self.cordf[c1][c2]*100))+" %"
            self.oran.setText(orn)
           
            cn1=self.percentdf[c1]*100
            cn1=cn1.to_frame()
            cn1[c1]=cn1.cumsum()
            cn1["c2"]=self.percentdf[c2]*100
            #cn2=cn2.to_frame()
            cn1[c2]=cn1["c2"].cumsum()
            self.figure.clear()
            plt.tight_layout()
            sns.set()   
            sns.axes_style("darkgrid")
            self.figure=sns.lineplot(data=cn1[[c1, c2]])
    
            fig = self.figure.get_figure()
            fig.savefig("output.png")  
            pixmap = QPixmap('output.png')
            self.label_pic.setPixmap(pixmap)
        except KeyError:
            print("Coin not found in binance. Please write correct coin ")


    def calculate_lagged_correlation(self):
        try:
            c1 = self.cn_1.text().upper() + "USDT"
            c2 = self.cn_2.text().upper() + "USDT"
            series1 = self.percentdf[c1].dropna()
            series2 = self.percentdf[c2].dropna()
            min_len = min(len(series1), len(series2))
            series1 = series1[:min_len]
            series2 = series2[:min_len]
            lags = range(-10, 11)
            cross_corrs = ccf(series1, series2, unbiased=False)[:len(lags)]
            max_lag = lags[np.argmax(np.abs(cross_corrs))]
            max_corr = np.max(np.abs(cross_corrs))
            
            # Period süresini saniyeye çevir
            period_seconds = {
                '1h': 3600, '2h': 7200, '4h': 14400, '1d': 86400, '1w': 604800
            }[self.period.currentText()]
            time_duration = max_lag * period_seconds / 3600  # Saat cinsinden
            
            result = "Lagged Cross-Correlation:\n"
            for lag, corr in zip(lags, cross_corrs):
                result += f"Lag {lag}: {corr:.4f}\n"
            result += f"\nMaksimum Korelasyon: {max_corr:.4f} (Lag {max_lag})\n"
            result += f"Tepkiler Arası Süre: {time_duration:.2f} saat"
            self.analysis_result.setText(result)
        except Exception as e:
            self.analysis_result.setText(str(e))

    def calculate_granger_causality(self):
        try:
            c1 = self.cn_1.text().upper() + "USDT"
            c2 = self.cn_2.text().upper() + "USDT"
            data = pd.concat([self.percentdf[c1], self.percentdf[c2]], axis=1).dropna()
            data.columns = ['series1', 'series2']
            result = grangercausalitytests(data, maxlag=4, verbose=False)
            output = "Granger Causality Test Results:\n"
            for lag, res in result.items():
                p_value = res[0]['ssr_ftest'][1]
                output += f"Lag {lag}: p-value = {p_value:.4f}\n"
            self.analysis_result.setText(output)
        except Exception as e:
            self.analysis_result.setText(str(e))

    def plot_wavelet_coherence(self):
        try:
            c1 = self.cn_1.text().upper() + "USDT"
            c2 = self.cn_2.text().upper() + "USDT"
            x = self.percentdf[c1].dropna().values
            y = self.percentdf[c2].dropna().values
            min_len = min(len(x), len(y))
            x = x[:min_len]
            y = y[:min_len]
            widths = np.arange(1, min_len // 2)
            cwt_x = cwt(x, ricker, widths)
            cwt_y = cwt(y, ricker, widths)
            cross = cwt_x * np.conj(cwt_y)
            S_cross = gaussian_filter(np.abs(cross)**2, sigma=1.0)
            S_xx = gaussian_filter(np.abs(cwt_x)**2, sigma=1.0)
            S_yy = gaussian_filter(np.abs(cwt_y)**2, sigma=1.0)
            coh = S_cross / np.sqrt(S_xx * S_yy + 1e-10)  # Avoid division by zero

            self.figure.clear()
            plt.imshow(coh, aspect='auto', cmap='jet')
            plt.colorbar()
            plt.title('Wavelet Coherence')
            plt.ylabel('Scale')
            plt.xlabel('Time')
            fig = self.figure.get_figure()
            fig.savefig("wavelet_output.png")
            pixmap = QPixmap('wavelet_output.png')
            self.label_pic.setPixmap(pixmap)  # Reuse the label or add new one
            self.analysis_result.setText("Wavelet Coherence plotted.")
        except Exception as e:
            self.analysis_result.setText(str(e))

    def calculate_var_model(self):
        try:
            c1 = self.cn_1.text().upper() + "USDT"
            c2 = self.cn_2.text().upper() + "USDT"
            data = pd.concat([self.percentdf[c1], self.percentdf[c2]], axis=1).dropna()
            model = VAR(data)
            results = model.fit(maxlags=4, ic='aic')
            summary = results.summary()
            self.analysis_result.setText(str(summary))
        except Exception as e:
            self.analysis_result.setText(str(e))
    
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Correlative Coin Finder"))
        font = QtGui.QFont()
        font.setBold(True)
        self.groupBox_2.setTitle(_translate("MainWindow", "Download New Data"))
        self.day.setItemText(0, _translate("MainWindow", "30 days"))
        self.day.setItemText(1, _translate("MainWindow", "90 days"))
        self.day.setItemText(2, _translate("MainWindow", "180 days"))
        self.day.setItemText(3, _translate("MainWindow", "1 year"))
        self.period.setItemText(0, _translate("MainWindow", "1h"))
        self.period.setItemText(1, _translate("MainWindow", "2h"))
        self.period.setItemText(2, _translate("MainWindow", "4h"))
        self.period.setItemText(3, _translate("MainWindow", "1d"))
        self.period.setItemText(4, _translate("MainWindow", "1w"))
        self.down.setText(_translate("MainWindow", "Download Data"))
        self.down.setFont(font)
        self.groupBox_3.setTitle(_translate("MainWindow", "Upload Saved Data"))
        self.label_2.setText(_translate("MainWindow", "Last Saved:"))
        self.date.setText(_translate("MainWindow", self.rd))
        self.load.setText(_translate("MainWindow", "Load Data"))
        self.load.setFont(font)
        self.groupBox_4.setTitle(_translate("MainWindow", "Find Correlative Coins"))
        
        self.pushButton_3.setText(_translate("MainWindow", "Get Correlations"))
        self.pushButton_3.setFont(font)
        self.groupBox_5.setTitle(_translate("MainWindow", "Draw Correlation Chart"))
        self.drw.setText("Draw")

        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Coin Name"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Correlation"))
    
    def refresh(self):
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.repaint()

if __name__ == "__main__":
    import sys
   
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())